### ISSUE TITLE
Error when a service is not attached to any network

### ISSUE THREAD

**Issue by Neirda24** [LeoVerto/docker-network-graph#10]
When a container declares no network, docker accepts it. But the tool fails with the following message:
```
Traceback (most recent call last):
  File "docker-net-graph.py", line 191, in <module>
    generate_graph(args.verbose, args.out)
  File "docker-net-graph.py", line 170, in generate_graph
    draw_link(g, networks, link)
  File "docker-net-graph.py", line 147, in draw_link
    color=networks[link.network_name].color
KeyError: 'none'
```

**Comment by LeoVerto** [comment]
Thank you for reporting this!
