### ISSUE TITLE
Error With host network_mode ? 

### ISSUE THREAD

**Issue by Xyaren** [LeoVerto/docker-network-graph#7]
```
Traceback (most recent call last):
  File "docker-net-graph.py", line 191, in <module>
    generate_graph(args.verbose, args.out)
  File "docker-net-graph.py", line 170, in generate_graph
    draw_link(g, networks, link)
  File "docker-net-graph.py", line 147, in draw_link
    color=networks[link.network_name].color
KeyError: 'host'
```

I'm getting this error on running the tool.

**Comment by metonymic-smokey** [comment]
@Xyaren I faced the same.  
As a stopgap, I added an if-condition along the lines of:
`if link.network.name != 'host'`.

That temporarily fixed the problem for me.

**Comment by LeoVerto** [comment]
Thanks for reporting this! And thanks to @metonymic-smokey for the fix!
